### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by nedbat** [landscapeio/pylint-django#69]
Can you give us an idea of what to expect with pull requests being merged, and new versions released?  A number of improvements are in the iXce fork: https://github.com/iXce/pylint-django

Should we continue to wait, or should we move onto a new fork?

**Comment by carlio** [comment]
Hi @nedbat . I am definitely hoping to get back to this soon - I was in a rather bad motorcycle crash a few months ago so that has taken up most of my time recently (see also https://github.com/landscapeio/landscape-issues/issues/210).  Mostly back in one piece now though, so I'm sorting out the various things that fell away. I will look into all the open PRs and issues in the coming weeks, sorry for being tardy! Turn out that a bleed in your brain really slows you down for a while :)

**Comment by nedbat** [comment]
Wow, Carl! Very sorry to hear the reason, but very glad to hear that you are back on a positive trend :)  Looking forward to the improvements.  I'd be glad to help get the pylint checkers moving. We're using them in-house for edX, and they are a big help.

**Comment by carlio** [comment]
Ok on it now! Sorry for delay :)

**Comment by nedbat** [comment]
Let me know how I can help.

**Comment by carlio** [comment]
@nedbat I just merged a bunch of PRs so testing the new master branch would be awesome! Seems to work for me but always good to get a second pair of eyes. Now I'll start digging through the open issues.
